version: '2'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data
    command: redis-server --port 6379 --requirepass "redis1357!"
    networks:
      - my_network
    
  mariadb:
    image: mariadb:10.5.9
    container_name: mariadb 
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4' # conf.d 우선
      - '--collation-server=utf8mb4_unicode_ci' # conf.d 우선
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: user1357!
    networks:
      - my_network
  
  pretest-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - version=0.5.0
    container_name: pretest-app
    ports:
      - "9090:9090"
    volumes:
      - ./config:/app/pretest/config
      - ./logs:/app/pretest/logs
    depends_on:
      - redis
      - mariadb
    networks:
      - my_network
        

networks:
  my_network:
    driver: bridge
